# Generated by Django 3.2.7 on 2021-10-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_delivery_time',
            field=models.DateTimeField(null=True),
        ),
    ]
