# Generated by Django 3.2.7 on 2021-10-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='name',
            field=models.CharField(default='N/A', max_length=45),
            preserve_default=False,
        ),
    ]
