# Generated by Django 3.2.7 on 2021-10-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_product_to_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='N/A', max_length=45),
            preserve_default=False,
        ),
    ]
