# Generated by Django 3.2.7 on 2021-10-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_toppings_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
