# Generated by Django 3.2.7 on 2021-10-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20211001_1718'),
    ]

    operations = [
    ]
