# Generated by Django 3.2.7 on 2021-10-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_toppings_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppingstopizza',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='toppingstopizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(to='index.Product'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='index.Toppings'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.area'),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.area'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.product'),
        ),
        migrations.AlterField(
            model_name='drink',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.product'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.customer'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.product'),
        ),
        migrations.DeleteModel(
            name='OrderToProduct',
        ),
        migrations.DeleteModel(
            name='ToppingsToPizza',
        ),
    ]
