# Generated by Django 3.2.7 on 2021-10-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_toppings_price'),
    ]

    operations = [
    ]
