# Generated by Django 3.2.7 on 2021-10-08 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20211005_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_delivery_time',
            field=models.DateTimeField(default='1900-01-01 00:00'),
            preserve_default=False,
        )
    ]
